In [11]:
import numpy as np
import pandas as pd

### PCA on Simple Numpy Array Data Done in Class

In [13]:
A = np.array([[4, 3, 1], [4, 1, 1], [2, 3, 4]])
print(A)

[[4 3 1]
 [4 1 1]
 [2 3 4]]


In [14]:
t = A.transpose()
t

array([[4, 4, 2],
       [3, 1, 3],
       [1, 1, 4]])

In [15]:
at = np.matmul(A, t)
at

array([[26, 20, 21],
       [20, 18, 15],
       [21, 15, 29]])

In [18]:
w, v= np.linalg.eig(at) # drop one column
print(v)
print(w)

[[-0.62245567 -0.69560878 -0.35871629]
 [-0.48796026  0.70326586 -0.51702216]
 [-0.61191807  0.14678408  0.77718126]]
[62.32304429  1.34852432  9.32843139]


In [29]:
w.sort(axis=-1)
print(w)
w[1:]

[ 1.34852432  9.32843139 62.32304429]


array([ 9.32843139, 62.32304429])

In [30]:
FVectors = np.delete(v, 2, axis=1)
print(FinalSelectedVectors)

[[-0.62245567 -0.69560878]
 [-0.48796026  0.70326586]
 [-0.61191807  0.14678408]]


In [31]:
AVectors = np.insert(FVectors,[2], [[0]], axis = 1) 
print(AppendedVectors)

[[-0.62245567 -0.69560878  0.        ]
 [-0.48796026  0.70326586  0.        ]
 [-0.61191807  0.14678408  0.        ]]


In [32]:
print(A.shape, AVectors.shape)

(3, 3) (3, 3)


In [33]:
PCA=np.matmul(A, AVectors)

print(PCA)

[[-4.56562153 -0.52585345  0.        ]
 [-3.589701   -1.93238517  0.        ]
 [-5.1564644   1.30571634  0.        ]]


### Iris Dataset PCA

In [45]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris



In [46]:
# Load a sample dataset (Iris dataset in this case)
data = load_iris()
X = data.data

# Standardize the data (centering and scaling)
mean = np.mean(X, axis=0)
std_dev = np.std(X, axis=0)
X = (X - mean) / std_dev



In [47]:
# Initialize PCA with the desired number of components
n_components = 2
pca = PCA(n_components=n_components)

# Fit and transform the data
X_pca = pca.fit_transform(X)



In [48]:
# Principal components
principal_components = pca.components_

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Variance explained by each component
explained_variance = pca.explained_variance_



In [49]:
print(explained_variance)

[2.93808505 0.9201649 ]


### PCA on Titanic Data

In [50]:
df = pd.read_csv("Train.csv")

In [51]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [52]:
dt = df.transpose()
dt

0    \
PassengerId                        1   
Survived                           0   
Pclass                             3   
Name         Braund, Mr. Owen Harris   
Sex                             male   
Age                             22.0   
SibSp                              1   
Parch                              0   
Ticket                     A/5 21171   
Fare                            7.25   
Cabin                            NaN   
Embarked                           S   

                                                           1    \
PassengerId                                                  2   
Survived                                                     1   
Pclass                                                       1   
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...   
Sex                                                     female   
Age                                                       38.0   
SibSp                                                        1   
Parch                                                        0   
Ticket                                                PC 17599   
Fare                                                   71.2833   
Cabin                                                      C85   
Embarked                                                     C   

                                2    \
PassengerId                       3   
Survived                          1   
Pclass                            3   
Name         Heikkinen, Miss. Laina   
Sex                          female   
Age                            26.0   
SibSp                             0   
Parch                             0   
Ticket             STON/O2. 3101282   
Fare                          7.925   
Cabin                           NaN   
Embarked                          S   

                                                      3    \
PassengerId                                             4   
Survived                                                1   
Pclass                                                  1   
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Sex                                                female   
Age                                                  35.0   
SibSp                                                   1   
Parch                                                   0   
Ticket                                             113803   
Fare                                                 53.1   
Cabin                                                C123   
Embarked                                                S   

                                  4                 5    \
PassengerId                         5                 6   
Survived                            0                 0   
Pclass                              3                 3   
Name         Allen, Mr. William Henry  Moran, Mr. James   
Sex                              male              male   
Age                              35.0               NaN   
SibSp                               0                 0   
Parch                               0                 0   
Ticket                         373450            330877   
Fare                             8.05            8.4583   
Cabin                             NaN               NaN   
Embarked                            S                 Q   

                                 6                               7    \
PassengerId                        7                               8   
Survived                           0                               0   
Pclass                             1                               3   
Name         McCarthy, Mr. Timothy J  Palsson, Master. Gosta Leonard   
Sex                             male                            male   
Age                             54.0                             2.0   
SibSp                              0                               3   
Parch  

In [62]:
x = df.mean()
x = list(x)
x

C:\Users\Bahadur\AppData\Local\Temp\ipykernel_2836\1678994915.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  x = df.mean()


[446.0,
 0.3838383838383838,
 2.308641975308642,
 29.69911764705882,
 0.5230078563411896,
 0.38159371492704824,
 32.204207968574636]

In [64]:
n_components = 1
pca = PCA(n_components=n_components)

# Fit and transform the data
X_pca = pca.fit_transform([x])


C:\Users\Bahadur\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\decomposition\_pca.py:525: RuntimeWarning: invalid value encountered in divide
  explained_variance_ = (S**2) / (n_samples - 1)


In [66]:
# Principal components
principal_components = pca.components_

# Explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Variance explained by each component
explained_variance = pca.explained_variance_


In [67]:
print(explained_variance)

[nan]
