In [ ]:
import pandas as pd
from numpy import *

## DataSet 1 – 1000 Cameras

Link: https://www.kaggle.com/datasets/crawford/1000-cameras-dataset

In [ ]:
# Reading the data into a dataframe

df1 = pd.read_csv("camera_dataset.csv")
df1

Model  Release date  Max resolution  Low resolution  \
0           Agfa ePhoto 1280          1997          1024.0           640.0   
1           Agfa ePhoto 1680          1998          1280.0           640.0   
2           Agfa ePhoto CL18          2000           640.0             0.0   
3           Agfa ePhoto CL30          1999          1152.0           640.0   
4     Agfa ePhoto CL30 Clik!          1999          1152.0           640.0   
...                      ...           ...             ...             ...   
1033         Toshiba PDR-M65          2001          2048.0          1024.0   
1034         Toshiba PDR-M70          2000          2048.0          1024.0   
1035         Toshiba PDR-M71          2001          2048.0          1024.0   
1036         Toshiba PDR-M81          2001          2400.0          1200.0   
1037         Toshiba PDR-T10          2002          1600.0           800.0   

      Effective pixels  Zoom wide (W)  Zoom tele (T)  Normal focus range  \
0                  0.0           38.0          114.0                70.0   
1                  1.0           38.0          114.0                50.0   
2                  0.0           45.0           45.0                 0.0   
3                  0.0           35.0           35.0                 0.0   
4                  0.0           43.0           43.0                50.0   
...                ...            ...            ...                 ...   
1033               3.0           38.0          114.0                10.0   
1034               3.0           35.0          105.0                80.0   
1035               3.0           35.0           98.0                80.0   
1036               3.0           35.0           98.0                80.0   
1037               1.0           38.0           38.0                40.0   

      Macro focus range  Storage included  Weight (inc. batteries)  \
0                  40.0               4.0                    420.0   
1                   0.0               4.0                    420.0   
2                   0.0               2.0                      0.0   
3                   0.0               4.0                      0.0   
4                   0.0              40.0                    300.0   
...                 ...               ...                      ...   
1033               10.0               8.0                    320.0   
1034                9.0              16.0                    390.0   
1035               10.0               8.0                    340.0   
1036               10.0              16.0                    340.0   
1037               20.0               8.0                    180.0   

      Dimensions   Price  
0           95.0   179.0  
1          158.0   179.0  
2            0.0   179.0  
3            0.0   269.0  
4          128.0  1299.0  
...          ...     ...  
1033       120.0    62.0  
1034       116.0    62.0  
1035       107.0    62.0  
1036       107.0    62.0  
1037        86.0   129.0  

[1038 rows x 13 columns]

In [ ]:
# dropping non-numeric column

df1.drop(columns = ["Model"], inplace = True)
df1

Release date  Max resolution  Low resolution  Effective pixels  \
0             1997          1024.0           640.0               0.0   
1             1998          1280.0           640.0               1.0   
2             2000           640.0             0.0               0.0   
3             1999          1152.0           640.0               0.0   
4             1999          1152.0           640.0               0.0   
...            ...             ...             ...               ...   
1033          2001          2048.0          1024.0               3.0   
1034          2000          2048.0          1024.0               3.0   
1035          2001          2048.0          1024.0               3.0   
1036          2001          2400.0          1200.0               3.0   
1037          2002          1600.0           800.0               1.0   

      Zoom wide (W)  Zoom tele (T)  Normal focus range  Macro focus range  \
0              38.0          114.0                70.0               40.0   
1              38.0          114.0                50.0                0.0   
2              45.0           45.0                 0.0                0.0   
3              35.0           35.0                 0.0                0.0   
4              43.0           43.0                50.0                0.0   
...             ...            ...                 ...                ...   
1033           38.0          114.0                10.0               10.0   
1034           35.0          105.0                80.0                9.0   
1035           35.0           98.0                80.0               10.0   
1036           35.0           98.0                80.0               10.0   
1037           38.0           38.0                40.0               20.0   

      Storage included  Weight (inc. batteries)  Dimensions   Price  
0                  4.0                    420.0        95.0   179.0  
1                  4.0                    420.0       158.0   179.0  
2                  2.0                      0.0         0.0   179.0  
3                  4.0                      0.0         0.0   269.0  
4                 40.0                    300.0       128.0  1299.0  
...                ...                      ...         ...     ...  
1033               8.0                    320.0       120.0    62.0  
1034              16.0                    390.0       116.0    62.0  
1035               8.0                    340.0       107.0    62.0  
1036              16.0                    340.0       107.0    62.0  
1037               8.0                    180.0        86.0   129.0  

[1038 rows x 12 columns]

In [ ]:
# Dealing with NaN values

for col in df1:
    df1[col].replace({nan: df1[col].mean()}, inplace = True)

In [ ]:
df1.isna().sum() # Values removed successfully

Release date               0
Max resolution             0
Low resolution             0
Effective pixels           0
Zoom wide (W)              0
Zoom tele (T)              0
Normal focus range         0
Macro focus range          0
Storage included           0
Weight (inc. batteries)    0
Dimensions                 0
Price                      0
dtype: int64

In [ ]:
# Making an array

arr1 = df1.to_numpy()
arr1

array([[1997., 1024.,  640., ...,  420.,   95.,  179.],
       [1998., 1280.,  640., ...,  420.,  158.,  179.],
       [2000.,  640.,    0., ...,    0.,    0.,  179.],
       ...,
       [2001., 2048., 1024., ...,  340.,  107.,   62.],
       [2001., 2400., 1200., ...,  340.,  107.,   62.],
       [2002., 1600.,  800., ...,  180.,   86.,  129.]])

In [ ]:
arr1_t = arr1.transpose()
arr1_t

array([[1997., 1998., 2000., ..., 2001., 2001., 2002.],
       [1024., 1280.,  640., ..., 2048., 2400., 1600.],
       [ 640.,  640.,    0., ..., 1024., 1200.,  800.],
       ...,
       [ 420.,  420.,    0., ...,  340.,  340.,  180.],
       [  95.,  158.,    0., ...,  107.,  107.,   86.],
       [ 179.,  179.,  179., ...,   62.,   62.,  129.]])

In [ ]:
product1 = matmul(arr1, arr1_t)
product1

array([[ 5684607.,  5951733.,  4688249., ...,  6931106.,  7404226.,
         6264663.],
       [ 5951733.,  6290366.,  4854089., ...,  7462139.,  8025371.,
         6680084.],
       [ 4688249.,  4854089.,  4445695., ...,  5329819.,  5555115.,
         5054527.],
       ...,
       [ 6931106.,  7462139.,  5329819., ...,  9395176., 10296360.,
         8188923.],
       [ 7404226.,  8025371.,  5555115., ..., 10296360., 11352488.,
         8892987.],
       [ 6264663.,  6680084.,  5054527., ...,  8188923.,  8892987.,
         7269394.]])

In [ ]:
eigenvalues1, eigenvectors1 = linalg.eig(product1)
print(eigenvalues1)
print(eigenvectors1)

[1.50004641e+10+0.00000000e+00j 5.86953361e+08+0.00000000e+00j
 3.98251197e+08+0.00000000e+00j ... 7.84335302e-24+0.00000000e+00j
 1.63691339e-24+3.44161695e-24j 1.63691339e-24-3.44161695e-24j]
[[ 1.71725630e-02+0.00000000e+00j  2.56832710e-03+0.00000000e+00j
   5.21374432e-02+0.00000000e+00j ...  1.29533823e-15+0.00000000e+00j
   8.60868315e-16-3.58254590e-16j  8.60868315e-16+3.58254590e-16j]
 [ 1.86057146e-02+0.00000000e+00j  3.35733951e-03+0.00000000e+00j
   5.08837354e-02+0.00000000e+00j ... -7.40489438e-17+0.00000000e+00j
  -6.43560295e-17+1.61568232e-17j -6.43560295e-17-1.61568232e-17j]
 [ 1.21023602e-02+0.00000000e+00j  1.68433974e-03+0.00000000e+00j
   7.12121397e-02+0.00000000e+00j ...  7.30621248e-17+0.00000000e+00j
  -1.21836774e-16+7.91398436e-17j -1.21836774e-16-7.91398436e-17j]
 ...
 [ 2.42541840e-02+0.00000000e+00j  1.25081522e-02+0.00000000e+00j
   3.40582485e-02+0.00000000e+00j ...  3.48431165e-15+0.00000000e+00j
   1.61597845e-15-2.40427886e-16j  1.61597845e-15+2.4042

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors1 = delete(eigenvectors1, argmin(eigenvalues1), axis = 1)

In [ ]:
print(arr1.shape)
print(eigenvectors1.shape)

(1038, 12)
(1038, 1037)


In [ ]:
arr1 = insert(arr1, [12], zeros((1038, 1026)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr1.shape)
print(eigenvectors1.shape)

(1038, 1038)
(1038, 1037)


In [ ]:
PCA1 = matmul(arr1, eigenvectors1)
PCA1

array([[8.02214031e+01+0.00000000e+00j, 1.41052078e+01+0.00000000e+00j,
        2.41836151e+02+0.00000000e+00j, ...,
        2.63419633e-12+0.00000000e+00j, 1.59834806e-12-6.75500663e-13j,
        1.59834806e-12+6.75500663e-13j],
       [8.54209782e+01+0.00000000e+00j, 1.52988006e+01+0.00000000e+00j,
        2.53405354e+02+0.00000000e+00j, ...,
        2.65173354e-12+0.00000000e+00j, 1.59730240e-12-6.73152591e-13j,
        1.59730240e-12+6.73152591e-13j],
       [5.19683602e+01+0.00000000e+00j, 7.05818013e+00+0.00000000e+00j,
        1.47870834e+02+0.00000000e+00j, ...,
        2.62202826e-12+0.00000000e+00j, 1.74075644e-12-7.16675272e-13j,
        1.74075644e-12+7.16675272e-13j],
       ...,
       [9.96104372e+01+0.00000000e+00j, 1.69427383e+01+0.00000000e+00j,
        3.12282214e+02+0.00000000e+00j, ...,
        2.55202923e-12+0.00000000e+00j, 1.45404372e-12-6.15199923e-13j,
        1.45404372e-12+6.15199923e-13j],
       [1.08418345e+02+0.00000000e+00j, 1.84464510e+01+0.00000000e+0

In [ ]:
U1, S1, V1 = linalg.svd(arr1, full_matrices = True)

In [ ]:
U1.shape, V1.shape, S1.shape

((1038, 1038), (1038, 1038), (1038,))

In [ ]:
print(U1)
print(V1)
print(S1)

[[-1.71725630e-02 -2.56832710e-03 -5.21374432e-02 ... -3.10707221e-02
  -2.75788004e-02 -3.39380288e-02]
 [-1.86057146e-02 -3.35733951e-03 -5.08837354e-02 ... -2.46006776e-02
  -1.01091871e-02 -3.06288462e-02]
 [-1.21023602e-02 -1.68433974e-03 -7.12121397e-02 ...  2.25183198e-02
   3.97663263e-02 -5.33899981e-03]
 ...
 [-2.42541840e-02 -1.25081522e-02 -3.40582485e-02 ...  9.95197947e-01
  -4.30608416e-03 -3.27335436e-04]
 [-2.69255948e-02 -1.42910811e-02 -2.65351829e-02 ... -4.53396419e-03
   9.93411036e-01 -1.05402282e-03]
 [-2.07981285e-02 -8.54162173e-03 -4.22208304e-02 ... -6.78148053e-04
  -1.16208636e-03  9.94186893e-01]]
[[-0.51150579 -0.67817069 -0.50244848 ...  0.          0.
   0.        ]
 [-0.08223116 -0.07674123 -0.09168106 ...  0.          0.
   0.        ]
 [-0.74708373  0.10879879  0.63540037 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.    

## DataSet 2 – 80 Cereals

Link: https://www.kaggle.com/datasets/crawford/80-cereals

In [ ]:
# Reading the data into a dataframe

df2 = pd.read_csv("cereal.csv")
df2

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [ ]:
# dropping non-numeric column

df2.drop(columns = ["name"], inplace = True)
df2

mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  potass  \
0    N    C        70        4    1     130   10.0    5.0       6     280   
1    Q    C       120        3    5      15    2.0    8.0       8     135   
2    K    C        70        4    1     260    9.0    7.0       5     320   
3    K    C        50        4    0     140   14.0    8.0       0     330   
4    R    C       110        2    2     200    1.0   14.0       8      -1   
..  ..  ...       ...      ...  ...     ...    ...    ...     ...     ...   
72   G    C       110        2    1     250    0.0   21.0       3      60   
73   G    C       110        1    1     140    0.0   13.0      12      25   
74   R    C       100        3    1     230    3.0   17.0       3     115   
75   G    C       100        3    1     200    3.0   17.0       3     110   
76   G    C       110        2    1     200    1.0   16.0       8      60   

    vitamins  shelf  weight  cups     rating  
0         25      3     1.0  0.33  68.402973  
1          0      3     1.0  1.00  33.983679  
2         25      3     1.0  0.33  59.425505  
3         25      3     1.0  0.50  93.704912  
4         25      3     1.0  0.75  34.384843  
..       ...    ...     ...   ...        ...  
72        25      3     1.0  0.75  39.106174  
73        25      2     1.0  1.00  27.753301  
74        25      1     1.0  0.67  49.787445  
75        25      1     1.0  1.00  51.592193  
76        25      1     1.0  0.75  36.187559  

[77 rows x 15 columns]

In [ ]:
# Dealing with other non-numeric columns

df2["mfr"].value_counts()

K    23
G    22
P     9
Q     8
R     8
N     6
A     1
Name: mfr, dtype: int64

In [ ]:
df2["type"].value_counts()

C    74
H     3
Name: type, dtype: int64

In [ ]:
df2["mfr"] = df2["mfr"].replace({"K": 1, "G": 2, "P": 3, "Q": 4,
                    "R": 5, "N": 6, "A": 7})
df2["type"] = df2["type"].replace({"C": 0, "H": 1})
df2

mfr  type  calories  protein  fat  sodium  fiber  carbo  sugars  potass  \
0     6     0        70        4    1     130   10.0    5.0       6     280   
1     4     0       120        3    5      15    2.0    8.0       8     135   
2     1     0        70        4    1     260    9.0    7.0       5     320   
3     1     0        50        4    0     140   14.0    8.0       0     330   
4     5     0       110        2    2     200    1.0   14.0       8      -1   
..  ...   ...       ...      ...  ...     ...    ...    ...     ...     ...   
72    2     0       110        2    1     250    0.0   21.0       3      60   
73    2     0       110        1    1     140    0.0   13.0      12      25   
74    5     0       100        3    1     230    3.0   17.0       3     115   
75    2     0       100        3    1     200    3.0   17.0       3     110   
76    2     0       110        2    1     200    1.0   16.0       8      60   

    vitamins  shelf  weight  cups     rating  
0         25      3     1.0  0.33  68.402973  
1          0      3     1.0  1.00  33.983679  
2         25      3     1.0  0.33  59.425505  
3         25      3     1.0  0.50  93.704912  
4         25      3     1.0  0.75  34.384843  
..       ...    ...     ...   ...        ...  
72        25      3     1.0  0.75  39.106174  
73        25      2     1.0  1.00  27.753301  
74        25      1     1.0  0.67  49.787445  
75        25      1     1.0  1.00  51.592193  
76        25      1     1.0  0.75  36.187559  

[77 rows x 15 columns]

In [ ]:
# Checking for NaN values

df2.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [ ]:
# Making an array

arr2 = df2.to_numpy()
arr2

array([[  6.      ,   0.      ,  70.      , ...,   1.      ,   0.33    ,
         68.402973],
       [  4.      ,   0.      , 120.      , ...,   1.      ,   1.      ,
         33.983679],
       [  1.      ,   0.      ,  70.      , ...,   1.      ,   0.33    ,
         59.425505],
       ...,
       [  5.      ,   0.      , 100.      , ...,   1.      ,   0.67    ,
         49.787445],
       [  2.      ,   0.      , 100.      , ...,   1.      ,   1.      ,
         51.592193],
       [  2.      ,   0.      , 110.      , ...,   1.      ,   0.75    ,
         36.187559]])

In [ ]:
arr2_t = arr2.transpose()
arr2_t

array([[  6.      ,   4.      ,   1.      , ...,   5.      ,   2.      ,
          2.      ],
       [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
          0.      ],
       [ 70.      , 120.      ,  70.      , ..., 100.      , 100.      ,
        110.      ],
       ...,
       [  1.      ,   1.      ,   1.      , ...,   1.      ,   1.      ,
          1.      ],
       [  0.33    ,   1.      ,   0.33    , ...,   0.67    ,   1.      ,
          0.75    ],
       [ 68.402973,  33.983679,  59.425505, ...,  49.787445,  51.592193,
         36.187559]])

In [ ]:
product2 = matmul(arr2, arr2_t)
product2

array([[105728.07561524,  50633.91467708, 133177.99011403, ...,
         73310.83035607,  68116.38938479,  53763.58412121],
       [ 50633.91467708,  34197.89043838,  57664.82728633, ...,
         32871.63054911,  31796.29252582,  25747.53638885],
       [133177.99011403,  57664.82728633, 179239.49954451, ...,
        107366.86516178,  98071.22212308,  81851.71146829],
       ...,
       [ 73310.83035607,  32871.63054911, 107366.86516178, ...,
         79573.23857963,  72173.31347142,  66645.1886034 ],
       [ 68116.38938479,  31796.29252582,  98071.22212308, ...,
         72173.31347142,  65710.75437855,  60404.74552813],
       [ 53763.58412121,  25747.53638885,  81851.71146829, ...,
         66645.1886034 ,  60404.74552813,  57967.10192638]])

In [ ]:
eigenvalues2, eigenvectors2 = linalg.eig(product2)
print(eigenvalues2)
print(eigenvectors2)

[ 4.16436327e+06+0.00000000e+00j  4.46507656e+05+0.00000000e+00j
  1.17649740e+05+0.00000000e+00j  2.11768924e+04+0.00000000e+00j
  3.20111148e+04+0.00000000e+00j  8.09216708e+02+0.00000000e+00j
  4.24353749e+02+0.00000000e+00j  1.63735277e+02+0.00000000e+00j
  5.02232499e+01+0.00000000e+00j  4.34745855e+01+0.00000000e+00j
  2.28467445e+01+0.00000000e+00j  1.93861560e+01+0.00000000e+00j
  2.58016206e+00+0.00000000e+00j  1.59977134e+00+0.00000000e+00j
  2.76796818e-01+0.00000000e+00j  9.12270390e-11+0.00000000e+00j
 -1.97080055e-11+7.94478481e-11j -1.97080055e-11-7.94478481e-11j
 -5.45219169e-11+0.00000000e+00j  4.93480455e-11+0.00000000e+00j
 -4.52872613e-11+0.00000000e+00j  4.31327889e-11+0.00000000e+00j
  4.08537516e-11+7.28089874e-12j  4.08537516e-11-7.28089874e-12j
 -3.96555297e-11+0.00000000e+00j -3.54886668e-11+5.94275242e-12j
 -3.54886668e-11-5.94275242e-12j  3.59757931e-11+0.00000000e+00j
 -2.59621120e-11+1.15011898e-11j -2.59621120e-11-1.15011898e-11j
 -3.06721557e-11+0.000000

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors2 = delete(eigenvectors2, argmin(eigenvalues2), axis = 1)

In [ ]:
print(arr2.shape)
print(eigenvectors2.shape)

(77, 15)
(77, 76)


In [ ]:
arr2 = insert(arr2, [15], zeros((77, 62)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr2.shape)
print(eigenvectors2.shape)

(77, 77)
(77, 76)


In [ ]:
PCA2 = matmul(arr2, eigenvectors2)
PCA2

array([[ -81.99304162 +0.j        ,   28.18737727 +0.j        ,
         -61.14618929 +0.j        , ...,   -6.07286593-33.47784022j,
          -3.88798761 +0.j        ,    8.08986517 +0.j        ],
       [ -51.29271636 +0.j        ,   35.16114407 +0.j        ,
         -63.64976953 +0.j        , ...,    9.02007081 -9.04304229j,
           5.9331335  +0.j        ,   -0.98393924 +0.j        ],
       [-100.4524153  +0.j        ,   25.29378124 +0.j        ,
         -62.90299743 +0.j        , ...,  -18.41869713-53.51945078j,
         -23.23434206 +0.j        ,   28.31974592 +0.j        ],
       ...,
       [ -72.92757089 +0.j        ,   16.52846879 +0.j        ,
         -45.75083228 +0.j        , ...,  -23.26089638-45.53609833j,
         -32.13301124 +0.j        ,   31.3929841  +0.j        ],
       [ -68.75501943 +0.j        ,   16.48723626 +0.j        ,
         -45.22612297 +0.j        , ...,  -20.23637175-41.06592662j,
         -27.44989832 +0.j        ,   26.64415295 +0.j        ]

In [ ]:
U2, S2, V2 = linalg.svd(arr2, full_matrices = True)

In [ ]:
U2.shape, V2.shape, S2.shape

((77, 77), (77, 77), (77,))

In [ ]:
print(U2)
print(V2)
print(S2)

[[-0.12989586 -0.26564198 -0.17660507 ... -0.17726963 -0.08467972
  -0.05261221]
 [-0.06349172 -0.17093721  0.17249209 ...  0.05457514  0.0424297
   0.10212164]
 [-0.18552086 -0.21145404 -0.36686998 ...  0.10301473 -0.03983589
  -0.00872795]
 ...
 [-0.13720771  0.0225635  -0.07758335 ...  0.90163883 -0.02785493
  -0.0381549 ]
 [-0.12523069  0.00488274 -0.03801216 ... -0.03867286  0.91491637
  -0.0520524 ]
 [-0.1156097   0.07023078  0.02039514 ... -0.05713048 -0.0411207
   0.93056498]]
[[-1.02573190e-02 -7.60139227e-05 -4.45925228e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.92738746e-03 -3.63238533e-04 -3.60262234e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.95776016e-02  1.69483897e-03  8.09828259e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000e+

## DataSet 3 – GroundHog Day Forecasts and Temperatures

Link: https://www.kaggle.com/datasets/groundhogclub/groundhog-day

In [ ]:
# Reading the data into a dataframe

df3 = pd.read_csv("groundhog.csv")
df3

Year Punxsutawney Phil  February Average Temperature  \
0         1886         No Record                           NaN   
1         1887       Full Shadow                           NaN   
2         1888       Full Shadow                           NaN   
3         1889         No Record                           NaN   
4         1890         No Shadow                           NaN   
..         ...               ...                           ...   
127       2013         No Shadow                         34.77   
128       2014       Full Shadow                         32.13   
129       2015       Full Shadow                         32.99   
130       2016         No Shadow                         39.47   
131  1901-2000               NaN                         33.82   

     February Average Temperature (Northeast)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   
..                                        ...   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   
131                                      22.5   

     February Average Temperature (Midwest)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
..                                      ...   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   
131                                    32.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                            NaN                        NaN   
1                                            NaN                        NaN   
2                                            NaN                        NaN   
3                                            NaN                        NaN   
4                                            NaN                        NaN   
..                                           ...                        ...   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   
131                                         26.5                      41.50   

     March Average Temperature (Northeast)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      NaN   
4                                      NaN   
..                                     ...   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   
131                                   32.3   

     March Average Temperature (Midwest)  \
0                                    NaN   
1                                    NaN   
2                                    NaN   
3                                    NaN   
4                                    NaN   
..                                   ...   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   
131                                 42.4   

     March Average Temperature (

In [ ]:
# Dealing with non-numeric column

df3["Punxsutawney Phil"].value_counts()

Full Shadow       102
No Shadow          16
No Record          12
Partial Shadow      1
Name: Punxsutawney Phil, dtype: int64

In [ ]:
df3["Punxsutawney Phil"] = df3["Punxsutawney Phil"].replace({"No Record": 0, "No Shadow": 1,
                                                             "Partial Shadow": 2, "Full Shadow": 3})
df3

Year  Punxsutawney Phil  February Average Temperature  \
0         1886                0.0                           NaN   
1         1887                3.0                           NaN   
2         1888                3.0                           NaN   
3         1889                0.0                           NaN   
4         1890                1.0                           NaN   
..         ...                ...                           ...   
127       2013                1.0                         34.77   
128       2014                3.0                         32.13   
129       2015                3.0                         32.99   
130       2016                1.0                         39.47   
131  1901-2000                NaN                         33.82   

     February Average Temperature (Northeast)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   
..                                        ...   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   
131                                      22.5   

     February Average Temperature (Midwest)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
..                                      ...   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   
131                                    32.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                            NaN                        NaN   
1                                            NaN                        NaN   
2                                            NaN                        NaN   
3                                            NaN                        NaN   
4                                            NaN                        NaN   
..                                           ...                        ...   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   
131                                         26.5                      41.50   

     March Average Temperature (Northeast)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      NaN   
4                                      NaN   
..                                     ...   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   
131                                   32.3   

     March Average Temperature (Midwest)  \
0                                    NaN   
1                                    NaN   
2                                    NaN   
3                                    NaN   
4                                    NaN   
..                                   ...   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   
131                                 42.4   

     March Average T

In [ ]:
# Dropping the last row (contains total of the stats from 1901 to 2000)

df3.drop(index = 131, axis = 0, inplace = True)
df3

Year  Punxsutawney Phil  February Average Temperature  \
0    1886                0.0                           NaN   
1    1887                3.0                           NaN   
2    1888                3.0                           NaN   
3    1889                0.0                           NaN   
4    1890                1.0                           NaN   
..    ...                ...                           ...   
126  2012                3.0                         37.51   
127  2013                1.0                         34.77   
128  2014                3.0                         32.13   
129  2015                3.0                         32.99   
130  2016                1.0                         39.47   

     February Average Temperature (Northeast)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                            NaN                        NaN   
1                                            NaN                        NaN   
2                                            NaN                        NaN   
3                                            NaN                        NaN   
4                                            NaN                        NaN   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      NaN   
4                                      NaN   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
0                                    NaN   
1                                    NaN   
2                                    NaN   
3                                    NaN   
4                                    NaN   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania)  
0                          

In [ ]:
df3.dtypes

Year                                            object
Punxsutawney Phil                              float64
February Average Temperature                   float64
February Average Temperature (Northeast)       float64
February Average Temperature (Midwest)         float64
February Average Temperature (Pennsylvania)    float64
March Average Temperature                      float64
March Average Temperature (Northeast)          float64
March Average Temperature (Midwest)            float64
March Average Temperature (Pennsylvania)       float64
dtype: object

In [ ]:
df3["Year"] = df3["Year"].astype('float64') # Typecasting

In [ ]:
# Dealing with NaN values

for col in df3:
    df3[col].replace({nan: df3[col].mean()}, inplace = True)

In [ ]:
df3.isna().sum() # Values removed successfully

Year                                           0
Punxsutawney Phil                              0
February Average Temperature                   0
February Average Temperature (Northeast)       0
February Average Temperature (Midwest)         0
February Average Temperature (Pennsylvania)    0
March Average Temperature                      0
March Average Temperature (Northeast)          0
March Average Temperature (Midwest)            0
March Average Temperature (Pennsylvania)       0
dtype: int64

In [ ]:
# Making an array

arr3 = df3.to_numpy()
arr3

array([[1.88600000e+03, 0.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       [1.88700000e+03, 3.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       [1.88800000e+03, 3.00000000e+00, 3.38027049e+01, ...,
        3.23680328e+01, 4.25688525e+01, 3.59081967e+01],
       ...,
       [2.01400000e+03, 3.00000000e+00, 3.21300000e+01, ...,
        2.60000000e+01, 3.80000000e+01, 3.03000000e+01],
       [2.01500000e+03, 3.00000000e+00, 3.29900000e+01, ...,
        2.78000000e+01, 4.16000000e+01, 3.16000000e+01],
       [2.01600000e+03, 1.00000000e+00, 3.94700000e+01, ...,
        3.88000000e+01, 4.95000000e+01, 4.34000000e+01]])

In [ ]:
arr3_t = arr3.transpose()
arr3_t

array([[1.88600000e+03, 1.88700000e+03, 1.88800000e+03, ...,
        2.01400000e+03, 2.01500000e+03, 2.01600000e+03],
       [0.00000000e+00, 3.00000000e+00, 3.00000000e+00, ...,
        3.00000000e+00, 3.00000000e+00, 1.00000000e+00],
       [3.38027049e+01, 3.38027049e+01, 3.38027049e+01, ...,
        3.21300000e+01, 3.29900000e+01, 3.94700000e+01],
       ...,
       [3.23680328e+01, 3.23680328e+01, 3.23680328e+01, ...,
        2.60000000e+01, 2.78000000e+01, 3.88000000e+01],
       [4.25688525e+01, 4.25688525e+01, 4.25688525e+01, ...,
        3.80000000e+01, 4.16000000e+01, 4.95000000e+01],
       [3.59081967e+01, 3.59081967e+01, 3.59081967e+01, ...,
        3.03000000e+01, 3.16000000e+01, 4.34000000e+01]])

In [ ]:
product3 = matmul(arr3, arr3_t)
product3

array([[3566314.00021119, 3568200.00021119, 3570086.00021119, ...,
        3806693.81175164, 3808569.92008115, 3813073.36055   ],
       [3568200.00021119, 3570096.00021119, 3571983.00021119, ...,
        3808716.81175164, 3810593.92008115, 3815092.36055   ],
       [3570086.00021119, 3571983.00021119, 3573871.00021119, ...,
        3810730.81175164, 3812608.92008115, 3817108.36055   ],
       ...,
       [3806693.81175164, 3808716.81175164, 3810730.81175164, ...,
        4063611.737     , 4065634.1176    , 4069916.5461    ],
       [3808569.92008115, 3810593.92008115, 3812608.92008115, ...,
        4065634.1176    , 4067837.7322    , 4071909.7703    ],
       [3813073.36055   , 3815092.36055   , 3817108.36055   , ...,
        4069916.5461    , 4071909.7703    , 4077010.2409    ]])

In [ ]:
eigenvalues3, eigenvectors3 = linalg.eig(product3)
print(eigenvalues3)
print(eigenvectors3)

[ 5.00047899e+08+0.00000000e+00j  7.86122583e+03+0.00000000e+00j
  5.80525791e+03+0.00000000e+00j  1.01559321e+03+0.00000000e+00j
  6.23380359e+02+0.00000000e+00j  3.06166586e+02+0.00000000e+00j
  1.29015971e+02+0.00000000e+00j  1.17510070e+02+0.00000000e+00j
  3.29865344e+01+0.00000000e+00j  2.61799236e+01+0.00000000e+00j
 -5.24508731e-08+0.00000000e+00j  3.29855949e-08+2.39577475e-08j
  3.29855949e-08-2.39577475e-08j -1.41416563e-08+3.67980495e-08j
 -1.41416563e-08-3.67980495e-08j  1.79011999e-08+1.96646461e-08j
  1.79011999e-08-1.96646461e-08j  1.10396024e-08+2.27499893e-08j
  1.10396024e-08-2.27499893e-08j -1.84074655e-08+1.66716908e-08j
 -1.84074655e-08-1.66716908e-08j -1.28022872e-09+2.46159352e-08j
 -1.28022872e-09-2.46159352e-08j -6.82659859e-09+2.28653452e-08j
 -6.82659859e-09-2.28653452e-08j -2.24545001e-08+5.34518548e-09j
 -2.24545001e-08-5.34518548e-09j  2.08793298e-08+0.00000000e+00j
  1.81736088e-08+7.00468491e-09j  1.81736088e-08-7.00468491e-09j
 -1.08683730e-08+1.554269

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors3 = delete(eigenvectors3, argmin(eigenvalues3), axis = 1)

In [ ]:
print(arr3.shape)
print(eigenvectors3.shape)

(131, 10)
(131, 130)


In [ ]:
arr3 = insert(arr3, [10], zeros((131, 121)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr3.shape)
print(eigenvectors3.shape)

(131, 131)
(131, 130)


In [ ]:
PCA3 = matmul(arr3, eigenvectors3)
PCA3

array([[ 181.99598505 +0.j        ,   60.30144813 +0.j        ,
         -34.79110218 +0.j        , ...,  -90.43928412 +9.99114557j,
         -90.43928412 -9.99114557j, -281.23740143 +0.j        ],
       [ 182.33392217 +0.j        ,   60.42752351 +0.j        ,
         -34.85273158 +0.j        , ...,  -90.49786268+10.00025738j,
         -90.49786268-10.00025738j, -281.44045293 +0.j        ],
       [ 182.41837282 +0.j        ,   60.45934781 +0.j        ,
         -34.8683516  +0.j        , ...,  -90.5453374 +10.0058352j ,
         -90.5453374 -10.0058352j , -281.59070968 +0.j        ],
       ...,
       [ 190.48216942 +0.j        ,   64.76520043 +0.j        ,
         -36.1705142  +0.j        , ...,  -96.53440068+10.8798948j ,
         -96.53440068-10.8798948j , -300.60107371 +0.j        ],
       [ 189.98765025 +0.j        ,   64.30261272 +0.j        ,
         -36.13144942 +0.j        , ...,  -96.83178947+10.91191377j,
         -96.83178947-10.91191377j, -300.35204731 +0.j        ]

In [ ]:
U3, S3, V3 = linalg.svd(arr3, full_matrices = True)

In [ ]:
U3.shape, V3.shape, S3.shape

((131, 131), (131, 131), (131,))

In [ ]:
print(U3)
print(V3)
print(S3)

[[-0.08445065 -0.0318243  -0.01562002 ... -0.06388922 -0.07602169
  -0.05178647]
 [-0.08449549 -0.03141703 -0.01533646 ...  0.13393831  0.16865568
  -0.16758452]
 [-0.08454015 -0.03092432 -0.01509958 ... -0.01962581 -0.28155194
  -0.0598212 ]
 ...
 [-0.09014434  0.15202855  0.0729801  ...  0.91938427 -0.04816783
  -0.00788458]
 [-0.09018878  0.21989484 -0.05708878 ... -0.0468498   0.85269386
  -0.00338733]
 [-0.09029326 -0.1340381  -0.07027002 ... -0.0089384  -0.0021117
   0.91684257]]
[[-0.99877731 -0.00126755 -0.01730764 ...  0.          0.
   0.        ]
 [ 0.04368526 -0.00252497 -0.26718062 ...  0.          0.
   0.        ]
 [ 0.01804829  0.00118576  0.16041125 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]
[2.23617508e+04 8.86635541e+01 7.61922431e+01 3.18683732e+01
 2.4

## DataSet 4 – USA Poverty Level Wages

Link: https://www.kaggle.com/datasets/asaniczka/poverty-level-wages-in-the-usa-dataset-1973-2022

In [ ]:
# Reading the data into a dataframe

df4 = pd.read_csv("poverty_level_wages.csv")
df4

year  annual_poverty-level_wage  hourly_poverty-level_wage  \
0   2022                      27733                      13.33   
1   2021                      25688                      12.35   
2   2020                      24544                      11.80   
3   2019                      24242                      11.65   
4   2018                      23809                      11.45   
5   2017                      23244                      11.18   
6   2016                      22755                      10.94   
7   2015                      22464                      10.80   
8   2014                      22422                      10.78   
9   2013                      22048                      10.60   
10  2012                      21715                      10.44   
11  2011                      21278                      10.23   
12  2010                      20634                       9.92   
13  2009                      20293                       9.76   
14  2008                      20364                       9.79   
15  2007                      19614                       9.43   
16  2006                      19074                       9.17   
17  2005                      18470                       8.88   
18  2004                      17867                       8.59   
19  2003                      17400                       8.37   
20  2002                      17014                       8.18   
21  2001                      16744                       8.05   
22  2000                      16286                       7.83   
23  1999                      15749                       7.57   
24  1998                      15413                       7.41   
25  1997                      15214                       7.31   
26  1996                      14893                       7.16   
27  1995                      14500                       6.97   
28  1994                      14167                       6.81   
29  1993                      13874                       6.67   
30  1992                      13536                       6.51   
31  1991                      13208                       6.35   
32  1990                      12740                       6.12   
33  1989                      12143                       5.84   
34  1988                      11629                       5.59   
35  1987                      11223                       5.40   
36  1986                      10858                       5.22   
37  1985                      10670                       5.13   
38  1984                      10317                       4.96   
39  1983                       9901                       4.76   
40  1982                       9499                       4.57   
41  1981                       8956                       4.31   
42  1980                       8181                       3.93   
43  1979                       7360                       3.54   
44  1978                       6718                       3.23   
45  1977                       6284                       3.02   
46  1976                       5914                       2.84   
47  1975                       5595                       2.69   
48  1974                       5158                       2.48   
49  1973                       4701                       2.26   

    0-75%_of_poverty_wages  75-100%_of_poverty_wages  \
0                      4.7                       7.5   
1                      3.8                       9.1   
2                      3.4                       8.6   
3                      4.4                      11.3   
4                      5.0                      13.0   
5                      5.1                      15.3   
6                      5.6                      15.2   
7                      6.7                      16.3   
8                      8.2                      16.2   
9                      6.4                      18.6   
10                   

In [ ]:
# Checking for NaN values

df4.isna().sum()

year                                        0
annual_poverty-level_wage                   0
hourly_poverty-level_wage                   0
0-75%_of_poverty_wages                      0
75-100%_of_poverty_wages                    0
share_below_poverty_wages                   0
100-125%_of_poverty_wages                   0
125-200%_of_poverty_wages                   0
200-300%_of_poverty_wages                   0
300%+_of_poverty_wages                      0
men_0-75%_of_poverty_wages                  0
men_75-100%_of_poverty_wages                0
men_share_below_poverty_wages               0
men_100-125%_of_poverty_wages               0
men_125-200%_of_poverty_wages               0
men_200-300%_of_poverty_wages               0
men_300%+_of_poverty_wages                  0
women_0-75%_of_poverty_wages                0
women_75-100%_of_poverty_wages              0
women_share_below_poverty_wages             0
women_100-125%_of_poverty_wages             0
women_125-200%_of_poverty_wages   

In [ ]:
# Making an array

arr4 = df4.to_numpy()
arr4

array([[2.0220e+03, 2.7733e+04, 1.3330e+01, ..., 1.5400e+01, 1.2300e+01,
        1.9200e+01],
       [2.0210e+03, 2.5688e+04, 1.2350e+01, ..., 1.6800e+01, 1.4200e+01,
        2.0000e+01],
       [2.0200e+03, 2.4544e+04, 1.1800e+01, ..., 1.4900e+01, 1.2000e+01,
        1.8600e+01],
       ...,
       [1.9750e+03, 5.5950e+03, 2.6900e+00, ..., 3.5000e+01, 2.7300e+01,
        4.7500e+01],
       [1.9740e+03, 5.1580e+03, 2.4800e+00, ..., 3.3700e+01, 2.4500e+01,
        4.9700e+01],
       [1.9730e+03, 4.7010e+03, 2.2600e+00, ..., 3.4900e+01, 2.7100e+01,
        4.8200e+01]])

In [ ]:
arr4_t = arr4.transpose()
arr4_t

array([[2.0220e+03, 2.0210e+03, 2.0200e+03, ..., 1.9750e+03, 1.9740e+03,
        1.9730e+03],
       [2.7733e+04, 2.5688e+04, 2.4544e+04, ..., 5.5950e+03, 5.1580e+03,
        4.7010e+03],
       [1.3330e+01, 1.2350e+01, 1.1800e+01, ..., 2.6900e+00, 2.4800e+00,
        2.2600e+00],
       ...,
       [1.5400e+01, 1.6800e+01, 1.4900e+01, ..., 3.5000e+01, 3.3700e+01,
        3.4900e+01],
       [1.2300e+01, 1.4200e+01, 1.2000e+01, ..., 2.7300e+01, 2.4500e+01,
        2.7100e+01],
       [1.9200e+01, 2.0000e+01, 1.8600e+01, ..., 4.7500e+01, 4.9700e+01,
        4.8200e+01]])

In [ ]:
product4 = matmul(arr4, arr4_t)
product4

array([[7.73216897e+08, 7.16500953e+08, 6.84772351e+08, ...,
        1.59171184e+08, 1.47049659e+08, 1.34373943e+08],
       [7.16500953e+08, 6.63967088e+08, 6.34577954e+08, ...,
        1.47727740e+08, 1.36499885e+08, 1.24758737e+08],
       [6.84772351e+08, 6.34577954e+08, 6.06497593e+08, ...,
        1.41324845e+08, 1.30596922e+08, 1.19378593e+08],
       ...,
       [1.59171184e+08, 1.47727740e+08, 1.41324845e+08, ...,
        3.52244728e+07, 3.27770535e+07, 3.02187843e+07],
       [1.47049659e+08, 1.36499885e+08, 1.30596922e+08, ...,
        3.27770535e+07, 3.05206913e+07, 2.81620499e+07],
       [1.34373943e+08, 1.24758737e+08, 1.19378593e+08, ...,
        3.02187843e+07, 2.81620499e+07, 2.60123518e+07]])

In [ ]:
eigenvalues4, eigenvectors4 = linalg.eig(product4)
print(eigenvalues4)
print(eigenvectors4)

[ 1.40335545e+10+0.00000000e+00j  2.58592892e+07+0.00000000e+00j
  9.01768942e+03+0.00000000e+00j  1.76191974e+03+0.00000000e+00j
  8.77685698e+02+0.00000000e+00j  2.25834612e+02+0.00000000e+00j
  1.50849049e+02+0.00000000e+00j  1.11601359e+02+0.00000000e+00j
  7.86208421e+01+0.00000000e+00j  3.28928276e+01+0.00000000e+00j
  2.23302163e+01+0.00000000e+00j  9.25381251e+00+0.00000000e+00j
  7.42428484e+00+0.00000000e+00j  4.76253737e+00+0.00000000e+00j
  2.57436116e+00+0.00000000e+00j  2.10417540e+00+0.00000000e+00j
  1.14205186e+00+0.00000000e+00j  6.08566379e-01+0.00000000e+00j
  2.37303832e-01+0.00000000e+00j  1.16338963e-01+0.00000000e+00j
  6.70587215e-02+0.00000000e+00j  5.38519361e-02+0.00000000e+00j
  3.79627646e-02+0.00000000e+00j  3.72540865e-02+0.00000000e+00j
  3.26031581e-02+0.00000000e+00j  2.82507761e-02+0.00000000e+00j
  1.90564355e-02+0.00000000e+00j  1.59949580e-02+0.00000000e+00j
  1.50484790e-02+0.00000000e+00j  1.05740830e-02+0.00000000e+00j
  7.58124846e-03+0.000000

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors4 = delete(eigenvectors4, argmin(eigenvalues4), axis = 1)

In [ ]:
print(arr4.shape)
print(eigenvectors4.shape)

(50, 33)
(50, 49)


In [ ]:
arr4 = insert(arr4, [33], zeros((50, 17)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr4.shape)
print(eigenvectors4.shape)

(50, 50)
(50, 49)


In [ ]:
PCA4 = matmul(arr4, eigenvectors4)
PCA4

array([[ 6577.97228237+0.j, -5114.69547424+0.j,  8301.10641118+0.j, ...,
           99.35797406+0.j,  -646.18743323+0.j, -1033.41823922+0.j],
       [ 6134.54455813+0.j, -4768.56199026+0.j,  7725.42900255+0.j, ...,
           86.76624739+0.j,  -597.38708192+0.j,  -955.81986327+0.j],
       [ 5884.10145127+0.j, -4575.6268269 +0.j,  7404.93791937+0.j, ...,
           80.7678877 +0.j,  -570.49911808+0.j,  -911.73070297+0.j],
       ...,
       [ 1780.52713688+0.j, -1358.69130462+0.j,  2057.64516919+0.j, ...,
          -26.34099737+0.j,  -119.154363  +0.j,  -202.44461299+0.j],
       [ 1682.88389373+0.j, -1285.14040408+0.j,  1936.68730925+0.j, ...,
          -27.37289251+0.j,  -109.98252788+0.j,  -186.10893296+0.j],
       [ 1585.73369268+0.j, -1207.08556962+0.j,  1805.72667666+0.j, ...,
          -30.1559833 +0.j,   -98.75958326+0.j,  -168.84694999+0.j]])

In [ ]:
U4, S4, V4 = linalg.svd(arr4, full_matrices = True)

In [ ]:
U4.shape, V4.shape, S4.shape

((50, 50), (50, 50), (50,))

In [ ]:
print(U4)
print(V4)
print(S4)

[[-0.23455014 -0.21337947 -0.27379856 ... -0.03356218 -0.11617725
   0.00440558]
 [-0.21739445 -0.16867012 -0.28023565 ...  0.13168349  0.13431198
   0.24133104]
 [-0.20779675 -0.14380201 -0.34273358 ...  0.03394529  0.05846595
  -0.10593734]
 ...
 [-0.04879989  0.26415092 -0.13557287 ...  0.34235556 -0.10147255
  -0.15440883]
 [-0.04513292  0.27349174 -0.20481763 ... -0.13400152  0.26689413
  -0.15240876]
 [-0.04129858  0.28339451 -0.15713479 ... -0.15999263 -0.21565472
   0.34095911]]
[[-1.11397379e-01 -9.93752523e-01 -4.77771969e-04 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 9.90358368e-01 -1.11559692e-01 -5.36220861e-05 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-5.58336598e-02  2.07446975e-03  6.89799531e-06 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000

## DataSet 5 – USA Unemployment

Link: https://www.kaggle.com/datasets/asaniczka/unemployment-rates-by-demographics-1978-2023

In [ ]:
# Reading the data into a dataframe

df5 = pd.read_csv("unemployment.csv")
df5

date  all  16-24  25-54  55-64  65+  less_than_hs  high_school  \
0    2023-07-01  3.6    7.8    3.1    2.4  2.7           7.0          4.8   
1    2023-06-01  3.6    7.8    3.1    2.4  2.8           7.1          4.8   
2    2023-05-01  3.6    7.9    3.0    2.4  2.8           7.1          4.8   
3    2023-04-01  3.6    7.9    3.0    2.4  2.8           7.1          4.8   
4    2023-03-01  3.6    8.0    3.0    2.5  2.8           7.1          4.8   
..          ...  ...    ...    ...    ...  ...           ...          ...   
531  1979-04-01  5.9   11.9    4.2    2.8  3.7           9.9          5.4   
532  1979-03-01  6.0   12.0    4.3    2.8  3.8           9.9          5.4   
533  1979-02-01  6.0   12.2    4.3    2.8  3.8           9.9          5.4   
534  1979-01-01  6.1   12.3    4.3    2.9  3.7          10.0          5.5   
535  1978-12-01  6.1   12.4    4.3    2.9  3.8          10.0          5.5   

     some_college  bachelor's_degree  ...  white_men_16-24  white_men_25-54  \
0             3.4                2.4  ...              7.0              2.5   
1             3.4                2.4  ...              7.0              2.5   
2             3.4                2.4  ...              7.0              2.5   
3             3.4                2.4  ...              7.0              2.5   
4             3.5                2.4  ...              7.1              2.5   
..            ...                ...  ...              ...              ...   
531           4.9                3.0  ...              9.4              2.8   
532           4.9                3.0  ...              9.4              2.8   
533           5.0                3.0  ...              9.6              2.8   
534           5.0                3.1  ...              9.7              2.9   
535           5.0                3.1  ...              9.7              2.9   

     white_men_55-64  white_men_65+  white_men_less_than_hs  \
0                2.1            2.4                     7.0   
1                2.1            2.5                     7.0   
2                2.1            2.5                     6.9   
3                2.2            2.5                     6.9   
4                2.2            2.5                     6.8   
..               ...            ...                     ...   
531              2.3            3.5                     7.5   
532              2.4            3.5                     7.5   
533              2.4            3.5                     7.6   
534              2.5            3.5                     7.6   
535              2.5            3.6                     7.6   

     white_men_high_school  white_men_some_college  \
0                      3.8                     2.8   
1                      3.8                     2.9   
2                      3.8                     2.9   
3                      3.8                     2.9   
4                      3.9                     2.9   
..                     ...                     ...   
531                    3.8                     3.6   
532                    3.8                     3.6   
533                    3.9                     3.6   
534                    3.9                     3.7   
535                    4.0                     3.7   

     white_men_bachelor's_degree  white_men_advanced_degree  \
0                            2.1                        1.6   
1                            2.1                        1.6   
2                            2.1                        1.6   
3                            2.1                        1.6   
4                            2.1                        1.7   
..                           ...                        ...   
531                          2.0                        1.3   
532                          2.1                        1.3   
533                          2.1                        1.4   
534                          2.1                        1.4   
535                          2.1      

In [ ]:
# dropping non-numeric column

df5.drop(columns = ["date"], inplace = True)
df5

all  16-24  25-54  55-64  65+  less_than_hs  high_school  some_college  \
0    3.6    7.8    3.1    2.4  2.7           7.0          4.8           3.4   
1    3.6    7.8    3.1    2.4  2.8           7.1          4.8           3.4   
2    3.6    7.9    3.0    2.4  2.8           7.1          4.8           3.4   
3    3.6    7.9    3.0    2.4  2.8           7.1          4.8           3.4   
4    3.6    8.0    3.0    2.5  2.8           7.1          4.8           3.5   
..   ...    ...    ...    ...  ...           ...          ...           ...   
531  5.9   11.9    4.2    2.8  3.7           9.9          5.4           4.9   
532  6.0   12.0    4.3    2.8  3.8           9.9          5.4           4.9   
533  6.0   12.2    4.3    2.8  3.8           9.9          5.4           5.0   
534  6.1   12.3    4.3    2.9  3.7          10.0          5.5           5.0   
535  6.1   12.4    4.3    2.9  3.8          10.0          5.5           5.0   

     bachelor's_degree  advanced_degree  ...  white_men_16-24  \
0                  2.4              1.7  ...              7.0   
1                  2.4              1.7  ...              7.0   
2                  2.4              1.7  ...              7.0   
3                  2.4              1.7  ...              7.0   
4                  2.4              1.7  ...              7.1   
..                 ...              ...  ...              ...   
531                3.0              2.0  ...              9.4   
532                3.0              2.0  ...              9.4   
533                3.0              2.0  ...              9.6   
534                3.1              2.0  ...              9.7   
535                3.1              2.0  ...              9.7   

     white_men_25-54  white_men_55-64  white_men_65+  white_men_less_than_hs  \
0                2.5              2.1            2.4                     7.0   
1                2.5              2.1            2.5                     7.0   
2                2.5              2.1            2.5                     6.9   
3                2.5              2.2            2.5                     6.9   
4                2.5              2.2            2.5                     6.8   
..               ...              ...            ...                     ...   
531              2.8              2.3            3.5                     7.5   
532              2.8              2.4            3.5                     7.5   
533              2.8              2.4            3.5                     7.6   
534              2.9              2.5            3.5                     7.6   
535              2.9              2.5            3.6                     7.6   

     white_men_high_school  white_men_some_college  \
0                      3.8                     2.8   
1                      3.8                     2.9   
2                      3.8                     2.9   
3                      3.8                     2.9   
4                      3.9                     2.9   
..                     ...                     ...   
531                    3.8                     3.6   
532                    3.8                     3.6   
533                    3.9                     3.6   
534                    3.9                     3.7   
535                    4.0                     3.7   

     white_men_bachelor's_degree  white_men_advanced_degree  \
0                            2.1                        1.6   
1                            2.1                        1.6   
2                            2.1                        1.6   
3                            2.1                        1.6   
4                            2.1                        1.7   
..                           ...                        ...   
531                          2.0                        1.3   
532                          2.1                        1.3   
533                          2.1                        1.4   
534                          2.1   

In [ ]:
# Checking for NaN values

df5.isna().sum()

all                            0
16-24                          0
25-54                          0
55-64                          0
65+                            0
                              ..
white_men_high_school          0
white_men_some_college         0
white_men_bachelor's_degree    0
white_men_advanced_degree      0
population_over_16             0
Length: 121, dtype: int64

In [ ]:
# Making an array

arr5 = df5.to_numpy()
arr5

array([[3.60000e+00, 7.80000e+00, 3.10000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.67002e+08],
       [3.60000e+00, 7.80000e+00, 3.10000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.66801e+08],
       [3.60000e+00, 7.90000e+00, 3.00000e+00, ..., 2.10000e+00,
        1.60000e+00, 2.66618e+08],
       ...,
       [6.00000e+00, 1.22000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63726e+08],
       [6.10000e+00, 1.23000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63516e+08],
       [6.10000e+00, 1.24000e+01, 4.30000e+00, ..., 2.10000e+00,
        1.40000e+00, 1.63272e+08]])

In [ ]:
arr5_t = arr5.transpose()
arr5_t

array([[3.60000e+00, 3.60000e+00, 3.60000e+00, ..., 6.00000e+00,
        6.10000e+00, 6.10000e+00],
       [7.80000e+00, 7.80000e+00, 7.90000e+00, ..., 1.22000e+01,
        1.23000e+01, 1.24000e+01],
       [3.10000e+00, 3.10000e+00, 3.00000e+00, ..., 4.30000e+00,
        4.30000e+00, 4.30000e+00],
       ...,
       [2.10000e+00, 2.10000e+00, 2.10000e+00, ..., 2.10000e+00,
        2.10000e+00, 2.10000e+00],
       [1.60000e+00, 1.60000e+00, 1.60000e+00, ..., 1.40000e+00,
        1.40000e+00, 1.40000e+00],
       [2.67002e+08, 2.66801e+08, 2.66618e+08, ..., 1.63726e+08,
        1.63516e+08, 1.63272e+08]])

In [ ]:
product5 = matmul(arr5, arr5_t)
product5

array([[7.12900680e+16, 7.12364006e+16, 7.11875392e+16, ...,
        4.37151695e+16, 4.36590990e+16, 4.35939505e+16],
       [7.12364006e+16, 7.11827736e+16, 7.11339490e+16, ...,
        4.36822605e+16, 4.36262323e+16, 4.35611329e+16],
       [7.11875392e+16, 7.11339490e+16, 7.10851579e+16, ...,
        4.36522987e+16, 4.35963089e+16, 4.35312541e+16],
       ...,
       [4.37151695e+16, 4.36822605e+16, 4.36522987e+16, ...,
        2.68062031e+16, 2.67718206e+16, 2.67318715e+16],
       [4.36590990e+16, 4.36262323e+16, 4.35963089e+16, ...,
        2.67718206e+16, 2.67374823e+16, 2.66975844e+16],
       [4.35939505e+16, 4.35611329e+16, 4.35312541e+16, ...,
        2.67318715e+16, 2.66975844e+16, 2.66577460e+16]])

In [ ]:
eigenvalues5, eigenvectors5 = linalg.eig(product5)
print(eigenvalues5)
print(eigenvectors5)

[ 2.53168648e+19   +0.j          4.70732971e+05   +0.j
  2.58393920e+04   +0.j          9.80810963e+03   +0.j
  7.79454737e+03   +0.j          3.89398683e+03   +0.j
  2.31296230e+03   +0.j          1.79086176e+03   +0.j
  1.60565565e+03  +49.91848854j  1.60565565e+03  -49.91848854j
 -1.41058717e+03   +0.j         -1.38072463e+03   +0.j
  9.56865409e+02 +743.65289182j  9.56865409e+02 -743.65289182j
  3.29548254e+02+1170.25566606j  3.29548254e+02-1170.25566606j
  5.63398597e+02+1059.62614697j  5.63398597e+02-1059.62614697j
 -1.02409561e+03 +724.2216877j  -1.02409561e+03 -724.2216877j
 -6.84411186e+02+1001.00880737j -6.84411186e+02-1001.00880737j
  1.10694249e+03 +207.16910801j  1.10694249e+03 -207.16910801j
  4.88495772e+01+1100.56887175j  4.88495772e+01-1100.56887175j
 -9.99741946e+02 +437.72238744j -9.99741946e+02 -437.72238744j
 -3.46147203e+02+1013.19694925j -3.46147203e+02-1013.19694925j
  9.82605575e+02   +0.j          2.10888894e+02 +756.13950679j
  2.10888894e+02 -756.13950679j  

In [ ]:
# Remove the eigenvector with lowest eigenvalue

eigenvectors5 = delete(eigenvectors5, argmin(eigenvalues5), axis = 1)

In [ ]:
print(arr5.shape)
print(eigenvectors5.shape)

(536, 121)
(536, 535)


In [ ]:
arr5 = insert(arr5, [121], zeros((536, 415)), axis = 1)

In [ ]:
# Multiplication now possible!

print(arr5.shape)
print(eigenvectors5.shape)

(536, 536)
(536, 535)


In [ ]:
PCA5 = matmul(arr5, eigenvectors5)
PCA5

array([[-13041110.93492279     +0.j        ,
          5505504.09178573     +0.j        ,
        -17171417.78853279     +0.j        , ...,
          4250864.65316167+436492.43057967j,
           170417.94384923     +0.j        ,
        -12924426.34067936     +0.j        ],
       [-13031293.568408       +0.j        ,
          5501359.52241363     +0.j        ,
        -17158491.09598066     +0.j        , ...,
          4247664.61990089+436163.85109252j,
           170289.70045361     +0.j        ,
        -12914696.74792923     +0.j        ],
       [-13022355.32127673     +0.j        ,
          5497586.17093346     +0.j        ,
        -17146721.99434229     +0.j        , ...,
          4244751.14790846+435864.71433986j,
           170173.01712159     +0.j        ,
        -12905838.4762516      +0.j        ],
       ...,
       [ -7996855.3868002      +0.j        ,
          3375955.07278761     +0.j        ,
        -10529546.88453605     +0.j        , ...,
          2606637.23

In [ ]:
U5, S5, V5 = linalg.svd(arr5, full_matrices = True)

In [ ]:
U5.shape, V5.shape, S5.shape

((536, 536), (536, 536), (536,))

In [ ]:
print(U5)
print(V5)
print(S5)

[[-0.05306517 -0.08772647  0.02634202 ... -0.02844224 -0.04605823
  -0.04000123]
 [-0.05302522 -0.08773507  0.02543594 ...  0.03747159  0.00302195
   0.05242269]
 [-0.05298885 -0.08788242  0.02571781 ...  0.09648313  0.05715509
   0.04497585]
 ...
 [-0.03253964  0.03577401  0.07769054 ...  0.7145302  -0.17746804
  -0.16133392]
 [-0.0324979   0.03707387  0.07738213 ... -0.16406394  0.66622782
  -0.23810758]
 [-0.03244941  0.03890043  0.07830402 ... -0.1710979  -0.25563269
   0.58437047]]
[[-2.77373101e-08 -5.67527576e-08 -2.30406062e-08 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.89716355e-02  1.17748808e-01  5.62582621e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.58455851e-02 -1.72617898e-02 -5.68642293e-02 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   1.00000000