# QUES # 1

In [43]:
# Load libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

#  Load data set using pandas library
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv("iris.csv", names=names,  skiprows=1)

# (b) Print the size of data set

print(dataset.shape)

print(dataset.head())

(150, 5)
   sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


### (c) Display the class distribution

In [44]:
print(dataset.groupby('class').size())

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


### (d) Now, divide your data using hold out approach (80% for training and 20% for testing) train / test dataset


In [45]:
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7
X_train_iris, X_test_iris, Y_train_iris, Y_test_iris = train_test_split(X, Y, test_size=t_size, random_state=seed)

print(X_test_iris)

[[5.9 3.0 5.1 1.8]
 [5.4 3.0 4.5 1.5]
 [5.0 3.5 1.3 0.3]
 [5.6 3.0 4.5 1.5]
 [4.9 2.5 4.5 1.7]
 [4.5 2.3 1.3 0.3]
 [6.9 3.1 4.9 1.5]
 [5.6 2.7 4.2 1.3]
 [4.8 3.4 1.6 0.2]
 [6.4 3.2 4.5 1.5]
 [6.7 3.0 5.0 1.7]
 [6.0 3.4 4.5 1.6]
 [5.2 4.1 1.5 0.1]
 [7.2 3.6 6.1 2.5]
 [5.2 3.4 1.4 0.2]
 [5.9 3.2 4.8 1.8]
 [6.7 2.5 5.8 1.8]
 [6.4 3.1 5.5 1.8]
 [5.1 3.8 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [5.8 2.7 3.9 1.2]
 [6.9 3.2 5.7 2.3]
 [6.1 2.9 4.7 1.4]
 [6.0 2.2 5.0 1.5]
 [7.2 3.0 5.8 1.6]
 [6.0 3.0 4.8 1.8]
 [6.2 2.9 4.3 1.3]
 [5.5 2.4 3.8 1.1]
 [5.8 2.7 5.1 1.9]
 [6.7 3.1 5.6 2.4]]


make predictions

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train_iris, Y_train_iris)

predictions = knn.predict(X_test_iris)

print("Accuracy Score: \n")
print(accuracy_score(Y_test_iris, predictions))

print("\nConfusion Matrix: \n")
print(confusion_matrix(Y_test_iris, predictions))

print("\nClassification : \n")
print(classification_report(Y_test_iris, predictions))

Accuracy Score: 

0.9

Confusion Matrix: 

[[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]

Classification : 

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



(f) Repeat (e) by changing the value of k (k=1, 2, 3,...., 10). Print only accuracy

In [47]:
print("Accuracy for different k values:")
for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_iris, Y_train_iris)
    predictions = knn.predict(X_test_iris)
    accuracy = accuracy_score(Y_test_iris, predictions)
    print(f"k = {k}: Accuracy = {accuracy:.4f}")


Accuracy for different k values:
k = 1: Accuracy = 0.9000
k = 2: Accuracy = 0.9333
k = 3: Accuracy = 0.9000
k = 4: Accuracy = 0.9333
k = 5: Accuracy = 0.9000
k = 6: Accuracy = 0.8667
k = 7: Accuracy = 0.8667
k = 8: Accuracy = 0.9000
k = 9: Accuracy = 0.9000
k = 10: Accuracy = 0.9000


(g) Repeat (e) by changing the value of seed (seed = 1, 2, 3, .... , 10). Print only accuracy

In [48]:
print("\nAccuracy for different seed values:")
for seed_val in range(1, 11):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size, random_state=seed_val)
    knn = KNeighborsClassifier()
    knn.fit(X_train, Y_train)
    predictions = knn.predict(X_test)
    accuracy = accuracy_score(Y_test, predictions)
    print(f"Accuracy = {accuracy:.4f}")



Accuracy for different seed values:
Accuracy = 1.0000
Accuracy = 1.0000
Accuracy = 0.9667
Accuracy = 0.9667
Accuracy = 0.9333
Accuracy = 0.9667
Accuracy = 0.9000
Accuracy = 0.9000
Accuracy = 1.0000
Accuracy = 0.9667


# QUES # 2

In [59]:
# Load the training dataset
columns = ['date', 'temperature', 'humidity', 'light', 'co2', 'humidity_ratio', 'occupancy']
train_data = pd.read_csv("datatraining.txt", names=columns, header=0)

# Dropping the 'date' attribute
train_data = train_data.drop('date', axis=1)

print(train_data.head())


   temperature  humidity  light     co2  humidity_ratio  occupancy
1        23.18   27.2720  426.0  721.25        0.004793          1
2        23.15   27.2675  429.5  714.00        0.004783          1
3        23.15   27.2450  426.0  713.50        0.004779          1
4        23.15   27.2000  426.0  708.25        0.004772          1
5        23.10   27.2000  426.0  704.50        0.004757          1


In [60]:
# (b) size of the dataset
print(train_data.shape)

# (c) class distribution
print("\nClass Dist:")
print(train_data.groupby('occupancy').size())


(8143, 6)

Class Dist:
occupancy
0    6414
1    1729
dtype: int64


In [65]:

# Load the two test datasets
test_dataset1 = pd.read_csv("datatest.txt", names=columns, header=0)
test_dataset2 = pd.read_csv("datatest2.txt", names=columns, header=0)

# Concatenate the two datasets
test_dataset = pd.concat([test_dataset1, test_dataset2], ignore_index=True)
test_dataset = test_dataset.drop('date', axis=1)

# Splitting features and target variable for both training and test datasets
X_trainOc = train_data.drop('occupancy', axis=1).values
Y_trainOc = train_data['occupancy'].values
X_testOc = test_dataset.drop('occupancy', axis=1).values
Y_testOc = test_dataset['occupancy'].values


(e) Apply kNN classifier


In [66]:
knn = KNeighborsClassifier()
knn.fit(X_trainOc, Y_trainOc)

predictions = knn.predict(X_testOc)

print("Accuracy Score: \n")
print(accuracy_score(Y_testOc, predictions))

print("\nConfusion Matrix: \n")
print(confusion_matrix(Y_testOc, predictions))

print("\nClassification : \n")
print(classification_report(Y_testOc, predictions))

Accuracy Score: 

0.9579608601111379

Confusion Matrix: 

[[9030  366]
 [ 156 2865]]

Classification : 

              precision    recall  f1-score   support

           0       0.98      0.96      0.97      9396
           1       0.89      0.95      0.92      3021

    accuracy                           0.96     12417
   macro avg       0.93      0.95      0.94     12417
weighted avg       0.96      0.96      0.96     12417



(f) calculating accuracy

In [67]:

print("Accuracy for different k values:")
for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trainOc, Y_trainOc)
    predictions = knn.predict(X_testOc)
    accuracy = accuracy_score(Y_testOc, predictions)
    print(f"k = {k}: Accuracy = {accuracy:.4f}")


Accuracy for different k values:
k = 1: Accuracy = 0.9473
k = 2: Accuracy = 0.9462
k = 3: Accuracy = 0.9530
k = 4: Accuracy = 0.9483
k = 5: Accuracy = 0.9580
k = 6: Accuracy = 0.9564
k = 7: Accuracy = 0.9641
k = 8: Accuracy = 0.9635
k = 9: Accuracy = 0.9648
k = 10: Accuracy = 0.9644


# QUES # 3

**Counter : for counting occurrences of items in a list. In kNN algorithm, Counter is used to identify the most common label among the top k neighbors.**

In [68]:
import numpy as np
import pandas as pd
from collections import Counter

# Chi-squared distance function
def chi_squared_distance(A, B):
    return 0.5 * np.sum([((a - b) ** 2) / (a + b)
                   for (a, b) in zip(A, B)])

# kNN classifier
def knn_classify(X_train, y_train, test_point, k=3):
    distances = [(y, chi_squared_distance(X, test_point)) for X, y in zip(X_train, y_train)]
    distances.sort(key=lambda x: x[1])
    top_k_labels = [item[0] for item in distances[:k]]
    most_common = Counter(top_k_labels).most_common(1)
    return most_common[0][0]



In [69]:
# using Iris dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv("iris.csv", names=names,  skiprows=1)

array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size, random_state=seed)

# Testing kNN classifier on Iris
print("Accuracy for different k values:")
for k in range(1, 11):
    y_pred = [knn_classify(X_train, Y_train, x, k=k) for x in X_test]
    accuracy = np.mean(y_pred == Y_test)
    print(f"k = {k}: Accuracy = {accuracy:.4f}")

Accuracy for different k values:
k = 1: Accuracy = 0.9000
k = 2: Accuracy = 0.9000
k = 3: Accuracy = 0.9000
k = 4: Accuracy = 0.8667
k = 5: Accuracy = 0.8667
k = 6: Accuracy = 0.8667
k = 7: Accuracy = 0.8667
k = 8: Accuracy = 0.8667
k = 9: Accuracy = 0.9000
k = 10: Accuracy = 0.9000


## for occupancy

In [72]:
# Using a smaller subset for quick verification
X_test_sample = X_testOc[:100]
Y_test_sample = Y_testOc[:100]

print("Accuracy for different k values for kNN classifier:")

for k in range(1, 11):
    y_pred = [knn_classify(X_trainOc, Y_trainOc, x, k=k) for x in X_test_sample]
    accuracy = np.mean(y_pred == Y_test_sample)
    print(f"k = {k}: Accuracy = {accuracy:.4f}")


Accuracy for different k values for kNN classifier:
k = 1: Accuracy = 0.9200
k = 2: Accuracy = 0.9200
k = 3: Accuracy = 0.9000
k = 4: Accuracy = 0.9100
k = 5: Accuracy = 0.9400
k = 6: Accuracy = 0.9500
k = 7: Accuracy = 0.9500
k = 8: Accuracy = 0.9600
k = 9: Accuracy = 0.9500
k = 10: Accuracy = 0.9600
