In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import zscore
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense, Dropout

df = pd.read_csv('Dataset1 (1).csv')
df.head(5)

8-QAM  Unnamed: 1  \
0    1.22474487139159 - 0.408248290463863i         NaN   
1   0.408248290463863 - 0.408248290463863i         NaN   
2   -1.22474487139159 - 0.408248290463863i         NaN   
3  -0.408248290463863 + 0.408248290463863i         NaN   
4   -1.22474487139159 + 0.408248290463863i         NaN   

                                    32-QAM  Unnamed: 3  \
0   -1.11803398874990 - 0.670820393249937i         NaN   
1  -0.223606797749979 + 0.223606797749979i         NaN   
2  -0.670820393249937 + 0.670820393249937i         NaN   
3   -0.223606797749979 - 1.11803398874990i         NaN   
4   -1.11803398874990 - 0.670820393249937i         NaN   

                                   128-QAM  Unnamed: 5  \
0  -0.773020682523926 - 0.993883734673619i         NaN   
1  -0.773020682523926 - 0.552157630374233i         NaN   
2    1.21474678682331 - 0.110431526074847i         NaN   
3  -0.993883734673619 + 0.110431526074847i         NaN   
4   0.773020682523926 + 0.331294578224540i         NaN   

                                      OFDM  Unnamed: 7  \
0  -0.773020682523926 - 0.993883734673619i         NaN   
1  -0.773020682523926 - 0.552157630374233i         NaN   
2    1.21474678682331 - 0.110431526074847i         NaN   
3  -0.993883734673619 + 0.110431526074847i         NaN   
4   0.773020682523926 + 0.331294578224540i         NaN   

                                           LTE  
0    -0.0227232682938660 + 0.0258335168130960i  
1    -0.0194529249087370 - 0.0121231728678195i  
2    0.0128642672165898 - 0.00221777822416349i  
3  0.00947980732883384 - 0.000851714289104194i  
4   -0.0396036825815445 + 0.00974998525029402i

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38400 entries, 0 to 38399
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   8-QAM       20000 non-null  object 
 1   Unnamed: 1  0 non-null      float64
 2   32-QAM      12000 non-null  object 
 3   Unnamed: 3  0 non-null      float64
 4   128-QAM     8571 non-null   object 
 5   Unnamed: 5  0 non-null      float64
 6   OFDM        8571 non-null   object 
 7   Unnamed: 7  0 non-null      float64
 8   LTE         38400 non-null  object 
dtypes: float64(4), object(5)
memory usage: 2.6+ MB


In [15]:

df.dropna(axis=1, how='all', inplace=True)
print(df)

                                         8-QAM  \
0        1.22474487139159 - 0.408248290463863i   
1       0.408248290463863 - 0.408248290463863i   
2       -1.22474487139159 - 0.408248290463863i   
3      -0.408248290463863 + 0.408248290463863i   
4       -1.22474487139159 + 0.408248290463863i   
...                                        ...   
38395                                      NaN   
38396                                      NaN   
38397                                      NaN   
38398                                      NaN   
38399                                      NaN   

                                        32-QAM  \
0       -1.11803398874990 - 0.670820393249937i   
1      -0.223606797749979 + 0.223606797749979i   
2      -0.670820393249937 + 0.670820393249937i   
3       -0.223606797749979 - 1.11803398874990i   
4       -1.11803398874990 - 0.670820393249937i   
...                                        ...   
38395                                      NaN   

In [16]:
# df['8-QAM '].head()
# df.columns
df.shape

(38400, 5)

In [17]:
df.columns

Index(['8-QAM', '32-QAM', '128-QAM', 'OFDM', 'LTE'], dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38400 entries, 0 to 38399
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   8-QAM    20000 non-null  object
 1   32-QAM   12000 non-null  object
 2   128-QAM  8571 non-null   object
 3   OFDM     8571 non-null   object
 4   LTE      38400 non-null  object
dtypes: object(5)
memory usage: 1.5+ MB


In [20]:
df.shape

(8571, 5)

In [19]:
# prompt: drop null rows

df.dropna(inplace=True)


In [21]:
# Remove white spaces
for col in df.columns:
    df[col] = df[col].str.replace(' ', '')

print(df)

                                      8-QAM  \
0       1.22474487139159-0.408248290463863i   
1      0.408248290463863-0.408248290463863i   
2      -1.22474487139159-0.408248290463863i   
3     -0.408248290463863+0.408248290463863i   
4      -1.22474487139159+0.408248290463863i   
...                                     ...   
8566  -0.408248290463863+0.408248290463863i   
8567   -1.22474487139159+0.408248290463863i   
8568  -0.408248290463863-0.408248290463863i   
8569   -1.22474487139159+0.408248290463863i   
8570   -1.22474487139159-0.408248290463863i   

                                     32-QAM  \
0      -1.11803398874990-0.670820393249937i   
1     -0.223606797749979+0.223606797749979i   
2     -0.670820393249937+0.670820393249937i   
3      -0.223606797749979-1.11803398874990i   
4      -1.11803398874990-0.670820393249937i   
...                                     ...   
8566   0.670820393249937+0.670820393249937i   
8567   0.670820393249937+0.670820393249937i   
8568  -0.223

In [ ]:
# for testing purpose, not included in actual code

# import pandas as pd
# import numpy as np

# # Example DataFrame
# data = {
#     '8-QAM': ['1.22474487139159 - 0.408248290463863i', '0.408248290463863 - 0.408248290463863i'],
#     '16-QAM': ['-1.11803398874990 - 0.670820393249937i', '-0.223606797749979 + 0.223606797749979i'],
#     '32-QAM': ['-1.11803398874990 - 0.670820393249937i', '-0.223606797749979 + 0.223606797749979i'],
#     '64-QAM': ['-1.11803398874990 - 0.670820393249937i', '-0.223606797749979 + 0.223606797749979i'],
#     '128-QAM': ['-0.773020682523926 - 0.993883734673619i', '-0.773020682523926 - 0.552157630374233i']
# }

# df = pd.DataFrame(data)

# # Remove white spaces
# for col in df.columns:
#     df[col] = df[col].str.replace(' ', '')

# # Add more rows
# for _ in range(1000):
#     df = df.append(pd.Series(df.iloc[0], index=df.columns), ignore_index=True)

# # Display the DataFrame
# print(df)


<ipython-input-125-739bb087d35e>:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.Series(df.iloc[0], index=df.columns), ignore_index=True)


                                     8-QAM  \
0      1.22474487139159-0.408248290463863i   
1     0.408248290463863-0.408248290463863i   
2      1.22474487139159-0.408248290463863i   
3      1.22474487139159-0.408248290463863i   
4      1.22474487139159-0.408248290463863i   
...                                    ...   
997    1.22474487139159-0.408248290463863i   
998    1.22474487139159-0.408248290463863i   
999    1.22474487139159-0.408248290463863i   
1000   1.22474487139159-0.408248290463863i   
1001   1.22474487139159-0.408248290463863i   

                                     16-QAM  \
0      -1.11803398874990-0.670820393249937i   
1     -0.223606797749979+0.223606797749979i   
2      -1.11803398874990-0.670820393249937i   
3      -1.11803398874990-0.670820393249937i   
4      -1.11803398874990-0.670820393249937i   
...                                     ...   
997    -1.11803398874990-0.670820393249937i   
998    -1.11803398874990-0.670820393249937i   
999    -1.11803398874990

In [22]:

df.tail(5)

8-QAM  \
8566  -0.408248290463863+0.408248290463863i   
8567   -1.22474487139159+0.408248290463863i   
8568  -0.408248290463863-0.408248290463863i   
8569   -1.22474487139159+0.408248290463863i   
8570   -1.22474487139159-0.408248290463863i   

                                     32-QAM  \
8566   0.670820393249937+0.670820393249937i   
8567   0.670820393249937+0.670820393249937i   
8568  -0.223606797749979+0.670820393249937i   
8569   -0.223606797749979+1.11803398874990i   
8570    0.670820393249937+1.11803398874990i   

                                    128-QAM  \
8566  -0.331294578224540+0.773020682523926i   
8567   0.993883734673619-0.773020682523926i   
8568   0.552157630374233+0.773020682523926i   
8569   0.773020682523926+0.331294578224540i   
8570  -0.552157630374233+0.331294578224540i   

                                       OFDM  \
8566  -0.331294578224540+0.773020682523926i   
8567   0.993883734673619-0.773020682523926i   
8568   0.552157630374233+0.773020682523926i   
8569   0.773020682523926+0.331294578224540i   
8570  -0.552157630374233+0.331294578224540i   

                                           LTE  
8566   -0.0134020184082583+0.0151515590934546i  
8567   0.0178589901836325+0.00442549831866548i  
8568  -0.00370077804665655-0.0160566215312079i  
8569  -0.0112847516557207+0.00911319731625038i  
8570   0.0112186969285489+0.00559665549095463i

In [23]:
# Apply complex conversion
for col in df.columns:
    df[col] = df[col].apply(lambda x: complex(x.replace('i', 'j') if 'i' in x else x + 'j'))

print(df)

                   8-QAM              32-QAM             128-QAM  \
0     1.224745-0.408248j -1.118034-0.670820j -0.773021-0.993884j   
1     0.408248-0.408248j -0.223607+0.223607j -0.773021-0.552158j   
2    -1.224745-0.408248j -0.670820+0.670820j  1.214747-0.110432j   
3    -0.408248+0.408248j -0.223607-1.118034j -0.993884+0.110432j   
4    -1.224745+0.408248j -1.118034-0.670820j  0.773021+0.331295j   
...                  ...                 ...                 ...   
8566 -0.408248+0.408248j  0.670820+0.670820j -0.331295+0.773021j   
8567 -1.224745+0.408248j  0.670820+0.670820j  0.993884-0.773021j   
8568 -0.408248-0.408248j -0.223607+0.670820j  0.552158+0.773021j   
8569 -1.224745+0.408248j -0.223607+1.118034j  0.773021+0.331295j   
8570 -1.224745-0.408248j  0.670820+1.118034j -0.552158+0.331295j   

                    OFDM                 LTE  
0    -0.773021-0.993884j -0.022723+0.025834j  
1    -0.773021-0.552158j -0.019453-0.012123j  
2     1.214747-0.110432j  0.012864-0.00221

In [24]:

# Feature engineering
df['real_8QAM'] = df['8-QAM'].apply(lambda x: x.real)
df['imag_8QAM'] = df['8-QAM'].apply(lambda x: x.imag)

df['real_32QAM'] = df['32-QAM'].apply(lambda x: x.real)
df['imag_32QAM'] = df['32-QAM'].apply(lambda x: x.imag)

df['real_128QAM'] = df['128-QAM'].apply(lambda x: x.real)
df['imag_128QAM'] = df['128-QAM'].apply(lambda x: x.imag)

df['real_OFDM'] = df['OFDM'].apply(lambda x: x.real)
df['imag_OFDM'] = df['OFDM'].apply(lambda x: x.imag)

df['real_LTE'] = df['LTE'].apply(lambda x: x.real)
df['imag_LTE'] = df['LTE'].apply(lambda x: x.imag)


# Create a synthetic target for classification
modulation_schemes = ['8-QAM', '32-QAM', '128-QAM','16-QAM', '64-QAM', 'OFDM', 'LTE']
df['target_class'] = np.random.choice(modulation_schemes, size=len(df))


In [26]:
# Predicting the modulation scheme of a single signal
# Creating a synthetic target for individual signal prediction
df['target_signal'] = np.random.choice(modulation_schemes, size=len(df))

# Drop original columns
df = df.drop(columns=['8-QAM', '32-QAM', '128-QAM','OFDM', 'LTE'])

# Split data into features and labels for classification
X_class = df.drop(columns=['target_class'])
y_class = df['target_class']

# Split data into features and labels for individual signal prediction
X_signal = df.drop(columns=['target_signal'])
y_signal = df['target_signal']


In [27]:
# Encode labels for classification
le = LabelEncoder()
df['target_class_encoded'] = le.fit_transform(y_class)

# Extracting only numeric features for standardization
numeric_features_class = X_class.select_dtypes(include=[np.number])

X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(numeric_features_class, df['target_class_encoded'], test_size=0.2, random_state=42)

# Standardize the features
scaler_class = StandardScaler()
X_train_scaled_class = scaler_class.fit_transform(X_train_class)
X_test_scaled_class = scaler_class.transform(X_test_class)

In [44]:
# Building neural network model for classification
model_class = Sequential()
model_class.add(Dense(128, activation='relu', input_dim=X_train_scaled_class.shape[1]))
model_class.add(Dense(64, activation='relu'))
model_class.add(Dense(len(modulation_schemes), activation='softmax'))  # Output layer for classification

# Compiling the model
model_class.compile(optimizer=Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Training the model
model_class.fit(X_train_scaled_class, y_train_class, epochs=1000, batch_size=32, validation_split=0.2)


Epoch 1/1000
172/172 [==============================] - 2s 5ms/step - loss: 1.9579 - accuracy: 0.1437 - val_loss: 1.9648 - val_accuracy: 0.1290
Epoch 2/1000
172/172 [==============================] - 1s 3ms/step - loss: 1.9404 - accuracy: 0.1605 - val_loss: 1.9617 - val_accuracy: 0.1312
Epoch 3/1000
172/172 [==============================] - 0s 2ms/step - loss: 1.9314 - accuracy: 0.1823 - val_loss: 1.9626 - val_accuracy: 0.1356
Epoch 4/1000
172/172 [==============================] - 0s 2ms/step - loss: 1.9265 - accuracy: 0.1820 - val_loss: 1.9651 - val_accuracy: 0.1305
Epoch 5/1000
172/172 [==============================] - 0s 2ms/step - loss: 1.9207 - accuracy: 0.1920 - val_loss: 1.9626 - val_accuracy: 0.1414
Epoch 6/1000
172/172 [==============================] - 1s 3ms/step - loss: 1.9158 - accuracy: 0.1895 - val_loss: 1.9647 - val_accuracy: 0.1363
Epoch 7/1000
172/172 [==============================] - 1s 3ms/step - loss: 1.9100 - accuracy: 0.2020 - val_loss: 1.9714 - val_accuracy:

## Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred_prob = model_class.predict(X_test_scaled_class)

y_pred_class = np.argmax(y_pred_prob, axis=1)

cm = confusion_matrix(y_test_class, y_pred_class)
print('Confusion Matrix:')
print(cm)

# classification report
cr = classification_report(y_test_class, y_pred_class)
print('Classification Report:')
print(cr)

54/54 [==============================] - 0s 2ms/step
Confusion Matrix:
[[26 19 26 48 40 29 29]
 [34 38 25 46 39 33 32]
 [25 39 34 39 42 33 38]
 [19 33 27 43 29 49 33]
 [23 30 33 43 43 41 50]
 [32 30 30 48 35 41 36]
 [27 26 43 51 37 35 34]]
Classification Report:
              precision    recall  f1-score   support

           0       0.14      0.12      0.13       217
           1       0.18      0.15      0.16       247
           2       0.16      0.14      0.15       250
           3       0.14      0.18      0.16       233
           4       0.16      0.16      0.16       263
           5       0.16      0.16      0.16       252
           6       0.13      0.13      0.13       253

    accuracy                           0.15      1715
   macro avg       0.15      0.15      0.15      1715
weighted avg       0.15      0.15      0.15      1715



In [47]:

y_signal_onehot = pd.get_dummies(df['target_signal']).values

# Dropping non-numeric columns for individual signal prediction
X_signal_numeric = X_signal.select_dtypes(include=[np.number])

X_train_signal, X_test_signal, y_train_signal, y_test_signal = train_test_split(X_signal_numeric, y_signal_onehot, test_size=0.2, random_state=42)

# Standardize
scaler_signal = StandardScaler()
X_train_scaled_signal = scaler_signal.fit_transform(X_train_signal)
X_test_scaled_signal = scaler_signal.transform(X_test_signal)

# Building neural network model
model_signal = Sequential()
model_signal.add(Dense(64, activation='relu', input_dim=X_train_scaled_signal.shape[1]))
model_signal.add(Dense(len(df['target_signal'].unique()), activation='softmax'))  # Output layer for individual signal prediction

# Compiling the model
model_signal.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Training the model
model_signal.fit(X_train_scaled_signal, y_train_signal, epochs=500, batch_size=32, validation_split=0.2)

Epoch 1/500
172/172 [==============================] - 2s 5ms/step - loss: 1.9868 - accuracy: 0.1450 - val_loss: 1.9672 - val_accuracy: 0.1407
Epoch 2/500
172/172 [==============================] - 0s 2ms/step - loss: 1.9553 - accuracy: 0.1543 - val_loss: 1.9628 - val_accuracy: 0.1443
Epoch 3/500
172/172 [==============================] - 0s 2ms/step - loss: 1.9477 - accuracy: 0.1663 - val_loss: 1.9605 - val_accuracy: 0.1429
Epoch 4/500
172/172 [==============================] - 0s 2ms/step - loss: 1.9424 - accuracy: 0.1690 - val_loss: 1.9630 - val_accuracy: 0.1305
Epoch 5/500
172/172 [==============================] - 0s 2ms/step - loss: 1.9393 - accuracy: 0.1732 - val_loss: 1.9642 - val_accuracy: 0.1407
Epoch 6/500
172/172 [==============================] - 0s 3ms/step - loss: 1.9365 - accuracy: 0.1787 - val_loss: 1.9640 - val_accuracy: 0.1407
Epoch 7/500
172/172 [==============================] - 0s 2ms/step - loss: 1.9349 - accuracy: 0.1725 - val_loss: 1.9643 - val_accuracy: 0.1363

## Evaluating the model on the test set

In [48]:

loss_signal, accuracy_signal = model_signal.evaluate(X_test_scaled_signal, y_test_signal)
print(f'Individual Signal Prediction Test Loss: {loss_signal}, Test Accuracy: {accuracy_signal}')


54/54 [==============================] - 0s 1ms/step - loss: 2.0638 - accuracy: 0.1429
Individual Signal Prediction Test Loss: 2.0637872219085693, Test Accuracy: 0.1428571492433548


## Generate confusion matrix

In [51]:

from sklearn.metrics import confusion_matrix, classification_report

y_pred_prob = model_class.predict(X_test_scaled_signal)

y_pred_class = np.argmax(y_pred_prob, axis=1)

cm = confusion_matrix(y_test_class, y_pred_class)
print('Confusion Matrix:')
print(cm)

# classification report
cr = classification_report(y_test_class, y_pred_class)
print('Classification Report:')
print(cr)

54/54 [==============================] - 0s 2ms/step
Confusion Matrix:
[[26 19 26 48 40 29 29]
 [34 38 25 46 39 33 32]
 [25 39 34 39 42 33 38]
 [19 33 27 43 29 49 33]
 [23 30 33 43 43 41 50]
 [32 30 30 48 35 41 36]
 [27 26 43 51 37 35 34]]
Classification Report:
              precision    recall  f1-score   support

           0       0.14      0.12      0.13       217
           1       0.18      0.15      0.16       247
           2       0.16      0.14      0.15       250
           3       0.14      0.18      0.16       233
           4       0.16      0.16      0.16       263
           5       0.16      0.16      0.16       252
           6       0.13      0.13      0.13       253

    accuracy                           0.15      1715
   macro avg       0.15      0.15      0.15      1715
weighted avg       0.15      0.15      0.15      1715

